apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/core/kafka
    repoURL: "https://github.com/dbgjerez/workshop-keda"
    targetRevision: 9-git-ops-structure
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
