service:
  version: 0.3.1
deployment:
  replicas: 1
  port: 8080
config:
  env:
    - name: KAFKA_BROKER
      value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
    - name: KAFKA_CAMERA_NEW_PICTURE_TOPIC
      value: camera-new-picture
