service:
  name: camera-api
  image: quay.io/dborrego/keda-camera-api
  version: 0.1

deployment:
  replicas: 2
  port: 8080
  health:
    liveness: /api/v1/health
    readiness: /api/v1/health
  resources: 
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 16Mi

kafka:
  tls:
    active: false
  acl: 
    active: false
  name: kafka
  topic:
    name: camera-new-picture

config:
  env: