service:
  version: 0.2
deployment:
  replicas: 1
  port: 8080
config:
  env:
    - name: KAFKA_BROKER
      value: kafka-kafka-routetls-bootstrap-kafka.apps.cluster-wffvj.wffvj.sandbox1320.opentlc.com:443