service:
  version: 0.2.1
deployment:
  replicas: 1
  port: 8080
config:
  env:
    - name: KAFKA_BROKER
      value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9093
    - name: CLIENT_CER_PEM_FILE
      value: "/certs/client.cer.pem"
    - name: CLIENT_KEY_PEM_FILE
      value: "/certs/client.key.pem"
    - name: SERVER_CER_PEM_FILE
      value: "/certs/server.cer.pem"
    