apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: book-crud
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: dev-backend
  template:
    metadata: 
      name: '{{env}}-book-crud'
      labels: 
        env: '{{env}}'
        type: app
    spec:
      destination:
        namespace: '{{namespace}}'
        server: "https://kubernetes.default.svc"
      source:
        path: apps/book-crud/gitops
        repoURL: "https://github.com/dbgjerez/workshop-keda"
        targetRevision: argocd
        helm:
          valueFiles:
            - '{{env}}.values.yaml'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true