apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: parking-crud
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: dev-data
  template:
    metadata: 
      name: '{{env}}-parking-crud'
      labels: 
        env: '{{env}}'
        type: app
        lang: go
    spec:
      destination:
        namespace: '{{namespace}}'
        server: "https://kubernetes.default.svc"
      source:
        path: apps/parking-crud/gitops
        repoURL: "https://github.com/dbgjerez/workshop-keda"
        targetRevision: 9-git-ops-structure
        helm:
          valueFiles:
            - '{{env}}.values.yaml'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true