apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: prometheus
spec:
  destination:
    namespace: kafka
    server: "https://kubernetes.default.svc"
  source:
    path: prometheus
    repoURL: "https://github.com/dbgjerez/workshop-keda"
    targetRevision: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
