apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: {{ .Release.Namespace }}
spec:
  secretTargetRef:
  - parameter: cert
    name: keda-kafka-connection
    key: server.cer.pem
  - parameter: key
    name: keda-kafka-connection
    key: client.cer.pem
  - parameter: keyPassword
    name: keda-kafka-connection
    key: client.key.pem
  - parameter: tls
    name: keda-kafka-connection
    key: tls