apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: {{ .Release.Namespace }}
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-connection
    key: sasl
  - parameter: username
    name: keda-kafka-connection
    key: username
  - parameter: password
    name: keda-kafka-connection
    key: password