service:
  name: book-crud
  image: quay.io/dborrego/book-crud
  version: 0.1

deployment:
  replicas: 1
  port: 8080
  health:
    liveness: /api/v1/health
    readiness: /api/v1/health
  resources: 
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

kafka:
  name: kafka
  topic:
    stock:
      name: stock

config:
  env: