service:
  name: book-crud
  image: quay.io/dborrego/book-crud
  version: 0.1

deployment:
  replicas: 1
  port: 8080
  health:
    liveness: /q/health/live
    readiness: /q/health/ready
  resources: 
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi

mariadb:
  database: parking
  user: parking

config:
  env: