apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  source:
    path: kafka
    repoURL: "https://github.com/dbgjerez/workshop-keda"
    targetRevision: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
