apiVersion: v1
kind: Service
metadata:
  name: mariadb-{{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: mariadb-{{ .Values.service.name | quote }}
    version: mariadb-{{ .Values.service.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3306
  selector:
    name: "mariadb-{{ .Values.service.name }}"