apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-consumer-{{ .Values.service.name }}
  namespace: kafka
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          name: cg-{{ .Values.service.name }}
          patternType: literal
          type: group
        operations: 
          - Read
        host: "*"
      - resource:
          name: {{ .Values.kafka.topic.stock.name }}
          patternType: literal
          type: topic
        operations: 
          - Read
        host: "*"