apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.service.name | quote }}
    app: {{ .Values.service.name | quote }}
    version: {{ .Values.service.version | quote }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.service.name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Values.service.name | quote }}
        version: {{ .Values.service.version | quote }}
    spec:
      serviceAccountName: {{ .Values.service.name }}
      {{- if .Values.kafka.acl.active }}
      volumes:
        - name: kafka
          secret: 
            secretName: "kafka-connection"
            items:
            - key: client.key.pem
              path: client.key.pem
            - key: client.cer.pem
              path: client.cer.pem
            - key: server.cer.pem
              path: server.cer.pem
      {{ end }}
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.service.image }}:{{ .Values.service.version }}
          {{- if .Values.kafka.acl.active }}
          volumeMounts:
            - name: kafka
              mountPath: "/certs"
              readOnly: true
          {{ end }}
          env:
          {{- range .Values.config.env }}
          {{- $envItem := . -}}
          {{- with $ }}
            - name: {{ $envItem.name | upper |  replace "-" "_" | quote}}
              value: {{ $envItem.value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.kafka.acl.active }}
            - name: CLIENT_CER_PEM_FILE
              value: "/certs/client.cer.pem"
            - name: CLIENT_KEY_PEM_FILE
              value: "/certs/client.key.pem"
            - name: SERVER_CER_PEM_FILE
              value: "/certs/server.cer.pem"
          {{- end }}    
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.health.liveness }}
              port: http
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.health.readiness }}
              port: http
            failureThreshold: 10
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
---