apiVersion: v1
kind: Service
metadata:
  name: mariadb-{{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: mariadb-{{ .Values.service.name }}
    version: mariadb-{{ .Values.service.version }}
spec:
  ports:
  - name: http
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mariadb-{{ .Values.service.name }}